name: salesforce-integration
services:
  sf-int:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: sf-int
    environment:
      SF_DOMAIN: business-computing-6655.my
      SERVER_PORT: 7011
      USERNAME: chandan-qv46@force.com
      PASSWORD: Admin@123eOO8UR8xaVqn9p1zXiGXdmokd
      CLIENT_ID: 3MVG9uk_cDhyHiA6jZtcttGmETQJUshkaOlqh5sB42OEAciIT_0W_RjjVju5z9YOwZetLdAQ1YvpUoKNMdVg3
      CLIENT_SECRET: 4515D316B52FF8948D4584E957AF22F1746FD8F2B6EF9603EACE4742C0EDCF6E
    ports:
      - "7011:7011"
