

sfq:
  salesforce:
    host: https://${SF_DOMAIN:platform-computing-8997.my}.salesforce.com
    base-path: ${sfq.salesforce.host}/services/data/v62.0/
    resource-path: /sobjects/{objectName}/{id}

spring:
  application:
    name: sf-quotation
  security:
    oauth2:
      client:
        registration:
          salesforce:
            provider: salesforce
            client-authentication-method: client_secret_post
            authorization-grant-type: password
            client-id: ${CLIENT_ID:3MVG929eOx29turELGtpTEdcTAF5oOTHa580YlXuN3nUeAmVKbM4Odlf.wI.uCeRcMjLhkXTdL5fLA4E.Z10o}
            client-secret: ${CLIENT_SECRET:AF90CF614C84519FE152D5AA2152CD30FBC9410361C2ADD03B967982507A8CB2}
            username: ${USERNAME:user-81zl@salesforce.com}
            password: ${PASSWORD:BAPIsabya@1232W21KGpOE9FUW3CzZwd6O5Xj}
        provider:
          salesforce:
            token-uri: ${sfq.salesforce.host}/services/oauth2/token
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /sf-quote

